name    'internetbydesign-peervpn'
version '0.0.1'
source 'http://github.com/internetbydesign/puppet-peervpn'
author 'internetbydesign'
license 'Apache License, Version 2.0'
summary 'PeerVPN for Linux'
description 'This module installs (from system packages) and configures PeerVPN'
project_page 'http://github.com/internetbydesign/puppet-peervpn'

dependency 'puppetlabs/stdlib', '>= 2.6.0'
dependency 'puppetlabs/apt', '>= 2.1.0'
